### ISSUE TITLE
Docker: Out of Memory

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1049]
- Issue type: Bug report

### Short description

I have been running the docker mariobehling/loklak image for three weeks.
I saw that http://loklak.quelltext.eu/ did not load.
I got this output:

    docker logs services_loklak_1 | tail -n 1
    Exception in thread "Thread-20735" java.lang.OutOfMemoryError: GC overhead limit exceeded

I appended the current [log](https://github.com/loklak/loklak_server/files/840586/all-output.txt).

### Environment

    docker ps
    5b2ebcd20ca8        mariobehling/loklak:latest      "./docker-cmd.sh"        9 weeks ago         Up 3 weeks          80/tcp, 443/tcp                            services_loklak_1

### Steps to reproduce

1.  docker start mariobehling/loklak
2.  wait for weeks
3.  look into the logs

### Expected behaviour

I would expect loklak to be able to recover from memory problems or adapt to it.
The website should load with a notification that there is an error. 

### Actual behaviour

Loklak seams to use up the memory it got and become unresponsive

### Usecase

I am running loklak with docker on my own machine.
### Description

- Show if such exceptions occur
- Notify me via mail that there is a problem ("Each program expands until it can read mail")
- scale down if there is not enough memory

**Tasks**

- [x] move Dockerfile to root #1050 
- [x] change docker-compose.yml  #1055
- [x] add a badge (travis/dockerhub) which adds the docker build status
- [x] change the dockerhub settings to use the dockerfile in the root folder

**Comment by yukiisbored** [comment]
It appears hub.docker.com/r/mariobehling/loklak isn't updated to the new image.

**Comment by niccokunzmann** [comment]
Error:

```
Step 5 : ADD bin /loklak_server/bin/
lstat bin: no such file or directory
```
[source](https://hub.docker.com/r/mariobehling/loklak/builds/biyd7c5jwcuhwj4azynbabo/)

**Comment by niccokunzmann** [comment]
I believe, we should move the Dockerfile to the repository root. What do you think @yukiisbored ?

**Comment by yukiisbored** [comment]
Yeah, that's due to the new changes made to the Docker Image.

**Comment by niccokunzmann** [comment]
I will create a PR.

**Comment by yukiisbored** [comment]
Out of Memory on Java applications is usual and the `Xmx` variable should be increased.

**Comment by smokingwheels** [comment]
Does the Docker setup have a hosts file?
If so I find this [site](http://winhelp2002.mvps.org/hosts.htm) really good and blocking unwanted stuff.

**Comment by niccokunzmann** [comment]
@yukiisbored I would close this and you can create a new Issue for clarity. This is already full of unrelated discussion to your solution. You can re-open it, if you like.

**Comment by niccokunzmann** [comment]
@smokingwheels Could you tell me more about your assumptions? I do not see how java using up memory relates to setting the ip for a domain name.

**Comment by yukiisbored** [comment]
This issue is now moved to https://github.com/loklak/loklak_server/issues/1060.
