### ISSUE TITLE
Question parser and answer templates

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#575]
We recently discussed the idea how to create a framework to implement "Q&A Apps" (lets call it that way for the moment). We want to discover typical question phrases and create a mechanism which consist of the following parts:
- a Parser for the question
- a generic search API which has just one input string (no other URL paramaters than that one) with a standard output format
- a result rendering module

With these parts, a "Q&A App" could be simply defined as 3-tuple:
```
(<regex for question>, <query formula>, <rendering method>)
```
To do this, the regular expressions parsing the question would have capture groups to match against the variable elements of the question. These variables would be set into the query formula. I suggest to use formulas as used by the Yahoo Query Console, see an example: https://developer.yahoo.com/yql/console/#h=select+*+from+local.search+where+query%3D%22sushi%22+and+location%3D%22san+francisco%2C+ca%22
Such formulas are similar to SQL. I believe that as an output format we should use simple tables. We can use SQL aggregations as well to create statistical data.
Finally, the result must be rendered. I think that we should have html patterns for this which we can append into one large result list. That should be used if several regular expressions for the same questions match.

That would cause the following development tasks:
- [x] create a Q&A Framework app which has an user input page and a result rendering page
- [x] create a loklak app which allows the user to add another (regex, query, rendering) tuple. That process would be called "creating a Q&A App". The user is then therefore able to create such apps.
- [x] create a new search api which takes a query in the form of a SQL term and outputs a table
- [ ] create a set of visualization modules for outputs of such tables
- [x] finally create an initial  list of (regex, query, rendering) tuples to get started

As add-on (to be done later) we can do:
- [ ] create search suggestions which makes examples of the question syntax. That would mean, we need an example string for each Q&A App triple (making it a quadruple)
- [ ] make a feed-back mechanism ("good answer", "unappropriate answer") so that we can make a self-learning process which pattern work best.

(check item(s) if issue was created)

Best of all, this not actually a complex thing. Would be funny to see if that actually works.

**Comment by Orbiter** [comment]
The visualization modules should be done in a similar way as the loklak_webclient 'views' https://github.com/loklak/loklak_webclient/tree/master/app/views
They should be like html code snippets. There must be two primary types:
- lists (like for a set of messages)
- visualizations (for String-Number pair lists)

**Comment by daminisatya** [comment]
#583

**Comment by mariobehling** [comment]
What is the best way then to make new `app views`? I like the idea of DuckDuckGo to host everything on Github and integrating it by using the API. I could imagine for example that we have a dedicated loklak_views repo, that can plug into loklak. Each app is in one folder. In this case we would also keep loklak_server leaner. We could also go the same way with loklak Q&A apps e.g. loklak_tuple. Would that fit with a framework?

**Comment by jig08** [comment]
@mariobehling Seems like a better idea. Not only would it help keep the `loklak_server` lighter but also help integrate other crawlers and parsers as `apps` and use them as plug-ins just like others.

**Comment by Orbiter** [comment]
The DuckDuckGo concept is good, but I believe there should be many 'views' that can be shared with different data extraction rules. Therefore such an app infrastructure should allow to omit the view definition and instead link to an existing one.

Shared 'views' could be i.e. Data tables, Maps, Link lists etc
DDG also allows to make very 'special' Instant Answers, like this one: https://duckduckgo.com/?q=Age+of+Empires+2+Cheat+Sheet&ia=cheatsheet
That would be something we don't have a framework, yet.

**Comment by Orbiter** [comment]
The search api is now implemented. You can try the "hello world" question:
http://loklak.org/api/susi.json?q=hello+world
This produces i.e.:
```
{
  "session": {"identity": {
    "type": "host",
    "name": "119.81.6.246",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "metadata": {
      "hits": 1,
      "offset": 0,
      "count": 1
    },
    "data": [{
      "0": "hello world",
      "1": "",
      "2": " world"
    }],
    "actions": [{
      "type": "answer",
      "expression": "Hi, I'm Susi"
    }]
  }]
}
```
The api returns a set of answers, in this case only one. All answers must be listed. Each answer has a data object and several actions. One possible Action is an "answer" which would be just a text line - like in this example. Other Actions may refer to the data part and request a visualization of that part.

The expected visualization for this example would be to simply print out the expression line "Hi, I'm Susi".

It will be possible to teach Susi how to react upon specific requests from the user. Currently there is only one configuration file for such reactions, see https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json

**Comment by mariobehling** [comment]
Closing this issue.
