### ISSUE TITLE
Update documentation with the following

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#69]
- [x] Trending hashtags API https://github.com/loklak/loklak_server/issues/63#issuecomment-118727692
- [x] Geocoding services API https://github.com/loklak/loklak_server/issues/62#issuecomment-118246927
- [x] Descending order etc.., https://github.com/loklak/loklak_server/issues/46#issuecomment-118874665

More to come as we find them

**Comment by zyzo** [comment]
* [ ] External Push service API #77

**Comment by mariobehling** [comment]
@sudheesh001 Please help with the documentation.
