### ISSUE TITLE
Propose and implement configuration options/settings of server as Web UI

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#848]
The server has a number of options, but we don't have a web UI where it is implemented. There are also configuration options that could be useful to run a server with limited resources, e.g. restrict the IP addresses that can query the server or control the number of results that are provided by default.

Please implement a UI that offers administrators a UI to control settings like these. 
- [ ] Make a list of configuration/settings
- [ ] Outline the solution
- [ ] Propose a UI
- [ ] Implement the UI

**Comment by mariobehling** [comment]
duplicate.
